=== LorenzoT94/Esercizi-Codifica-di-Testi/esercizio8.dtd
<!ELEMENT radice (text)>
<!ELEMENT text (giorno, attività, giornata+, ore+)>
<!ELEMENT giorno(#PCDATA)>
<!ELEMENT attività(#PCDATA)>
<!ELEMENT giornata(#PCDATA)>
<!ELEMENT ore(#PCDATA | giornata)*>
<!ATTLIST giornata
momento (pomeriggio | sera)#REQUIRED>

=== LorenzoT94/Esercizi-Codifica-di-Testi/Esercizio8Giusto.xml
<?xml version='1.0' encoding='utf-8'?><!--Esempio GIUSTO:-->
<!DOCTYPE radice SYSTEM "Esercizio8.dtd">
<radice>
<text>
    <giorno>Lunedi'</giorno>
    <attivita> momenti di studio </attivita>
    <giornata momento ="pomeriggio"/>
    <ore>
    	15-16:matematica
    </ore>
    <ore>
    	16-17:italiano
    </ore>
    <ore>
    	17-18:storia
    </ore>
    <ore>
    	18-<giornata momento ="sera"/>19:biologia
    </ore>
    <ore>
    	19-20:geografia
    </ore>
    <ore>
    	20-21:fisica
    </ore>
</text>
</radice>
